login.validate:
    path: /auth/validate
    defaults: { _controller: AppBundle:User:validateAuth }
    methods: [POST]

token.validate:
    path: /token/validate
    defaults: { _controller: AppBundle:User:validateToken }
    methods: [POST]

user.current:
    path: /user/current
    defaults: { _controller: AppBundle:User:getCurrentUser }
    methods: [POST]

user.register:
    path: /user/register
    defaults: { _controller: AppBundle:User:register }

lab.new:
    path: /laboratory/add
    defaults: { _controller: AppBundle:Laboratory:addNew }
    methods: [POST]

laborant.routes:
    prefix: /laborant
    resource: '@AppBundle/Resources/config/routing/laborant.yml'
    type: rest

laboratory.routes:
    prefix: /laboratory
    resource: '@AppBundle/Resources/config/routing/laboratory.yml'
    type: rest

student.routes:
    prefix: /student
    resource: '@AppBundle/Resources/config/routing/student.yml'
    type: rest
