login.validate:
    path: /auth/validate
    defaults: { _controller: AppBundle:User:validateAuth }
    methods: [POST]

token.validate:
    path: /token/validate
    defaults: { _controller: AppBundle:User:validateToken }
    methods: [POST]

user.routes:
    prefix: /user
    resource: '@AppBundle/Resources/config/routing/user.yml'
    type: rest

laborant.routes:
    prefix: /laborant
    resource: '@AppBundle/Resources/config/routing/laborant.yml'
    type: rest

laboratory.routes:
    prefix: /laboratory
    resource: '@AppBundle/Resources/config/routing/laboratory.yml'
    type: rest

student.routes:
    prefix: /student
    resource: '@AppBundle/Resources/config/routing/student.yml'
    type: rest

attendance.get:
    path: /attendance
    defaults: { _controller: AppBundle:User:getAttendance }
    methods: [POST]
    type: rest

attendance.set:
    path: /attendance/set
    defaults: { _controller: AppBundle:User:setAttendance }
    methods: [POST]
    type: rest