AppBundle\Entity\Attendance:
    type: entity
    table: attendance
    id:
        id:
            type: smallint
            generator:
                strategy: AUTO

    fields:
        attendance:
            type: integer

    manyToOne:
        laboratory:
            targetEntity: AppBundle\Entity\Laboratory
            cascade: ["persist"]
            inversedBy: attendance
            joinColumn:
                name: laboratory_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE

        student:
            targetEntity: AppBundle\Entity\Student
            cascade: ["persist"]
            inversedBy: attendance
            joinColumn:
                name: student_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE