AppBundle\Entity\Laboratory:
    type: entity
    table: laboratories
    id:
        id:
            type: smallint
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255

        year:
            type: smallint

        count:
            type: smallint


    manyToOne:
        laborant:
            targetEntity: AppBundle\Entity\Laborant
            inversedBy: laboratories

    oneToMany:
        attendance:
            targetEntity: AppBundle\Entity\Attendance
            mappedBy: laboratory

    manyToMany:
        students:
            targetEntity: AppBundle\Entity\Student
            mappedBy: laboratories