AppBundle\Entity\Student:
    type: entity
    table: students

    id:
        id:
            type: smallint
            generator:
                strategy: AUTO

    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        CNP:
            type: string
            length: 13
        group:
            type: string
            length: 8
            column: group_name


    oneToMany:
        attendance:
            targetEntity: AppBundle\Entity\Attendance
            cascade: ["persist"]
            mappedBy: student


    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE


    manyToMany:
        laboratories:
            targetEntity: AppBundle\Entity\Laboratory
            inversedBy: students
            joinTable:
                name: students_laboratories
                joinColumns:
                    student_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    laboratory_id:
                        referencedColumnName: id
                        onDelete: CASCADE