AppBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        username:
            type: string
            length: 255

        passwordHash:
            type: string
            length: 64

        role:
            type: string
            nullable: true

        salt:
            type: string
            length: 6

        webToken:
            type: string

        email:
            type: string
            length: 255